# Data Analysis with Pandas

## Overview
This notebook covers essential data analysis techniques using Pandas, one of the most popular Python libraries for data manipulation and analysis.

### Topics Covered:
1. **Loading & Exploring Data** - Reading CSV files and understanding data structure
2. **Data Inspection** - Examining data types and checking for missing values
3. **Data Cleaning** - Handling missing values and preparing data for analysis
4. **Data Transformation** - Renaming columns, type conversion, and applying functions
5. **Data Aggregation** - Grouping data and computing aggregate statistics
6. **Data Joining** - Merging multiple DataFrames using different join types

---

In [2]:
# Import necessary libraries
import pandas as pd
import numpy as np

## 1. Loading & Exploring Data

In this section, we'll load a CSV file and examine its structure to understand the data we're working with.

In [3]:
# Load the CSV file into a Pandas DataFrame
df = pd.read_csv("data.csv")

# Display the first 5 rows to get an overview of the data
print("First 5 rows of the dataset:")
display(df.head())

print("\nLast 5 rows of the dataset:")
# Display the last 5 rows to check the end of the data
display(df.tail())

First 5 rows of the dataset:

         Date Category  Value   Product  Sales Region
0  2023-01-01        A   28.0  Product1  754.0   East
1  2023-01-02        B   39.0  Product3  110.0  North
2  2023-01-03        C   32.0  Product2  398.0   East
3  2023-01-04        B    8.0  Product1  522.0   East
4  2023-01-05        B   26.0  Product3  869.0  North

Last 5 rows of the dataset:

          Date Category  Value   Product  Sales Region
45  2023-02-15        B   99.0  Product2  599.0   West
46  2023-02-16        B    6.0  Product1  938.0  South
47  2023-02-17        B   69.0  Product3  143.0   West
48  2023-02-18        C   65.0  Product3  182.0  North
49  2023-02-19        C   11.0  Product3  708.0  North

In [4]:
# Check the data types of all columns in the dataset
# This shows whether columns are numeric, string, datetime, etc.
print("Data types of each column:")
print(df.dtypes)

Data types of each column:
Date         object
Category     object
Value       float64
Product      object
Sales       float64
Region       object
dtype: object

### Understanding Data Types

It's important to know the data types of each column in your dataset. This helps identify potential issues and determines how to process the data correctly.

In [5]:
# Check if there are any missing values in each column
# Returns True if the column has at least one missing value, False otherwise
print("Columns with missing values:")
print(df.isnull().any(axis=0))

Columns with missing values:
Date        False
Category    False
Value        True
Product     False
Sales        True
Region      False
dtype: bool

## 2. Inspecting Missing Values

Missing values (NaN - Not a Number) can affect our analysis. It's crucial to identify and handle them appropriately.

In [6]:
# Count the number of missing values in each column
# This gives us a summary of how many NaN values exist in each column
print("Count of missing values per column:")
print(df.isnull().sum())

Count of missing values per column:
Date        0
Category    0
Value       3
Product     0
Sales       4
Region      0
dtype: int64

In [7]:
### Strategy 1: Fill Missing Values with a Constant (0)
# Create a new DataFrame with missing values filled with 0
df_filled = df.fillna(0)
print("First few rows after filling with 0:")
display(df_filled.head())

First few rows after filling with 0:

         Date Category  Value   Product  Sales Region
0  2023-01-01        A   28.0  Product1  754.0   East
1  2023-01-02        B   39.0  Product3  110.0  North
2  2023-01-03        C   32.0  Product2  398.0   East
3  2023-01-04        B    8.0  Product1  522.0   East
4  2023-01-05        B   26.0  Product3  869.0  North

## 3. Data Cleaning - Handling Missing Values

There are several strategies to handle missing values:
- **Fill with a constant value** - Replace NaN with 0, -1, or other constants
- **Fill with statistical value** - Use mean, median, or mode to fill missing values
- **Forward/Backward fill** - Propagate values from adjacent rows
- **Drop rows/columns** - Remove rows or columns with missing values

In [8]:
### Strategy 2: Fill Missing Values with Column Mean
# Calculate the mean of the 'Value' column
# Use this mean to fill any missing values in that column
# This preserves the distribution of the data better than using a constant
df['Value_fillNA'] = df['Value'].fillna(df['Value'].mean())

print("Data after filling 'Value' column with mean:")
display(df.head())

Data after filling 'Value' column with mean:

         Date Category  Value   Product  Sales Region  Value_fillNA
0  2023-01-01        A   28.0  Product1  754.0   East          28.0
1  2023-01-02        B   39.0  Product3  110.0  North          39.0
2  2023-01-03        C   32.0  Product2  398.0   East          32.0
3  2023-01-04        B    8.0  Product1  522.0   East           8.0
4  2023-01-05        B   26.0  Product3  869.0  North          26.0

In [9]:
### Renaming Columns
# Rename a column for better readability or consistency
# Using a dictionary mapping old column names to new column names
# inplace=True modifies the original DataFrame
df.rename(columns={'Date': 'Sale Date'}, inplace=True)

print("Column names after renaming:")
print(df.head())

Column names after renaming:
    Sale Date Category  Value   Product  Sales Region  Value_fillNA
0  2023-01-01        A   28.0  Product1  754.0   East          28.0
1  2023-01-02        B   39.0  Product3  110.0  North          39.0
2  2023-01-03        C   32.0  Product2  398.0   East          32.0
3  2023-01-04        B    8.0  Product1  522.0   East           8.0
4  2023-01-05        B   26.0  Product3  869.0  North          26.0

## 4. Data Transformation - Renaming & Type Conversion

In this section, we'll learn how to rename columns and convert data types to match our analysis requirements.

In [10]:
### Type Conversion
# Convert data type of a column to another type
# First fill missing values with the mean, then convert to integer
# This is useful when you need numeric data for calculations
df["Value_new"] = df['Value'].fillna(df['Value'].mean()).astype(int)

print("Data after type conversion to int:")
display(df.head())

Data after type conversion to int:

    Sale Date Category  Value   Product  Sales Region  Value_fillNA  Value_new
0  2023-01-01        A   28.0  Product1  754.0   East          28.0         28
1  2023-01-02        B   39.0  Product3  110.0  North          39.0         39
2  2023-01-03        C   32.0  Product2  398.0   East          32.0         32
3  2023-01-04        B    8.0  Product1  522.0   East           8.0          8
4  2023-01-05        B   26.0  Product3  869.0  North          26.0         26

In [11]:
# Use a lambda function to apply a transformation to each element in the 'Value' column
# In this example, we multiply each value by 2
# Lambda is a quick way to create anonymous functions for simple operations
df["New Value"] = df['Value'].apply(lambda x: x * 2)

print("Data after applying lambda function (multiply by 2):")
display(df.head())

Data after applying lambda function (multiply by 2):

,Sale Date,Category,Value,Product,Sales,Region,Value_fillNA,Value_new,New Value
0,2023-01-01,A,28.0,Product1,754.0,East,28.0,28,56.0
1,2023-01-02,B,39.0,Product3,110.0,North,39.0,39,78.0
2,2023-01-03,C,32.0,Product2,398.0,East,32.0,32,64.0
3,2023-01-04,B,8.0,Product1,522.0,East,8.0,8,16.0
4,2023-01-05,B,26.0,Product3,869.0,North,26.0,26,52.0

### Applying Functions to Columns

The `apply()` method allows you to apply a function to each element in a column. We can use lambda functions for quick, inline operations or custom functions for complex logic.

In [12]:
### Grouping by Single Column
# Group data by 'Product' and calculate the mean of 'Value' for each product
grouped_mean = df.groupby('Product')['Value'].mean()
print("Mean Value by Product:")
display(grouped_mean)

# Group data by 'Product' and calculate the sum of 'Value' for each product
grouped_sum = df.groupby('Product')['Value'].sum()
print("\nSum of Values by Product:")
display(grouped_sum)

Mean Value by Product:

Product
Product1    46.214286
Product2    52.800000
Product3    55.166667
Name: Value, dtype: float64

Sum of Values by Product:

Product
Product1    647.0
Product2    792.0
Product3    993.0
Name: Value, dtype: float64

## 5. Data Aggregation & Grouping

Grouping is a powerful technique to organize data by categories and compute statistics for each group. Common aggregation functions include `sum()`, `mean()`, `count()`, `std()`, and `median()`.

In [13]:
### Grouping by Multiple Columns
# Group by both 'Product' and 'Region' to see sales by product in each region
# This creates a hierarchical grouping with combinations of both columns
grouped_product_region = df.groupby(['Product', 'Region'])['Value'].sum()
print("Sum of Values by Product and Region (Multi-level grouping):")
display(grouped_product_region)

Sum of Values by Product and Region (Multi-level grouping):

Product   Region
Product1  East      292.0
          North       9.0
          South     100.0
          West      246.0
Product2  East       56.0
          North     127.0
          South     181.0
          West      428.0
Product3  East      202.0
          North     203.0
          South     215.0
          West      373.0
Name: Value, dtype: float64

In [14]:
### Multiple Aggregation Functions
# Apply multiple aggregate functions to the same grouping
# Using .agg() with a list of function names applies all functions to each group
grouped_aggr = df.groupby("Region")['Value'].agg(['sum', 'mean', 'std', 'median', 'count'])

print("Multiple statistics by Region:")
print("- sum: Total of all values")
print("- mean: Average value")
print("- std: Standard deviation (spread of data)")
print("- median: Middle value")
print("- count: Number of records")
print()
display(grouped_aggr)

Multiple statistics by Region:
- sum: Total of all values
- mean: Average value
- std: Standard deviation (spread of data)
- median: Middle value
- count: Number of records

           sum       mean        std  median  count
Region
East     550.0  42.307692  29.440292    32.0     13
North    339.0  37.666667  27.037012    39.0      9
South    496.0  62.000000  30.076094    66.5      8
West    1047.0  61.588235  25.992929    60.0     17

## 6. Data Joining & Merging

Merging combines two DataFrames based on a common column (key). Different join types control which rows are retained:
- **Inner Join**: Keep only rows where the key exists in both DataFrames
- **Left Join**: Keep all rows from the left DataFrame, fill missing values with NaN
- **Right Join**: Keep all rows from the right DataFrame, fill missing values with NaN
- **Outer Join**: Keep all rows from both DataFrames, fill missing values with NaN

In [15]:
# Create sample DataFrames to demonstrate merging
df1 = pd.DataFrame({
    'Key': ['A', 'B', 'C'],
    'Value1': [1, 2, 3]
})

df2 = pd.DataFrame({
    'Key': ['A', 'B', 'D'],
    'Value2': [4, 5, 6]
})

print("Left DataFrame (df1):")
display(df1)
print("\nRight DataFrame (df2):")
display(df2)

# INNER JOIN: Keep only rows where 'Key' exists in both DataFrames
print("\n--- INNER JOIN ---")
print("Result: Only 'A' and 'B' are kept (they exist in both DataFrames)")
display(pd.merge(df1, df2, on='Key', how='inner'))

# LEFT JOIN: Keep all rows from left DataFrame
print("\n--- LEFT JOIN ---")
print("Result: All rows from df1 (A, B, C), 'D' from df2 is not included")
display(pd.merge(df1, df2, on='Key', how='left'))

# RIGHT JOIN: Keep all rows from right DataFrame
print("\n--- RIGHT JOIN ---")
print("Result: All rows from df2 (A, B, D), 'C' from df1 is not included")
display(pd.merge(df1, df2, on='Key', how='right'))

# OUTER JOIN: Keep all rows from both DataFrames
print("\n--- OUTER JOIN ---")
print("Result: All unique keys from both DataFrames (A, B, C, D)")
display(pd.merge(df1, df2, on='Key', how='outer'))

Left DataFrame (df1):

  Key  Value1
0   A       1
1   B       2
2   C       3

Right DataFrame (df2):

  Key  Value2
0   A       4
1   B       5
2   D       6

--- INNER JOIN ---
Result: Only 'A' and 'B' are kept (they exist in both DataFrames)

  Key  Value1  Value2
0   A       1       4
1   B       2       5

--- LEFT JOIN ---
Result: All rows from df1 (A, B, C), 'D' from df2 is not included

  Key  Value1  Value2
0   A       1     4.0
1   B       2     5.0
2   C       3     NaN

--- RIGHT JOIN ---
Result: All rows from df2 (A, B, D), 'C' from df1 is not included

  Key  Value1  Value2
0   A     1.0       4
1   B     2.0       5
2   D     NaN       6

--- OUTER JOIN ---
Result: All unique keys from both DataFrames (A, B, C, D)

  Key  Value1  Value2
0   A     1.0     4.0
1   B     2.0     5.0
2   C     3.0     NaN
3   D     NaN     6.0

---

## Summary & Key Takeaways

### Essential Pandas Operations:
1. **Loading Data** - Use `pd.read_csv()` to import data
2. **Data Inspection** - Check data types and missing values
3. **Data Cleaning** - Handle missing values with appropriate strategies
4. **Data Transformation** - Rename columns, convert types, apply functions
5. **Data Aggregation** - Group data and compute statistics
6. **Data Merging** - Combine DataFrames using different join types

### Best Practices:
- Always inspect your data before analysis
- Handle missing values appropriately for your use case
- Use meaningful column names for better readability
- Apply transformations that make sense for your data types
- Verify results after grouping and merging operations

### Next Steps:
- Explore more advanced Pandas features like pivot tables, time-series analysis
- Learn data visualization with Matplotlib and Seaborn
- Practice with real-world datasets to reinforce these concepts