# Reading Data from Multiple Sources

## Overview
This notebook demonstrates how to read data from various sources using Pandas. In real-world data analysis, data comes from many different formats and locations.

### Topics Covered:
1. **JSON Data** - Reading and writing JSON data
2. **Web Data** - Reading CSV files directly from URLs
3. **HTML Tables** - Extracting tables from web pages
4. **Excel Files** - Reading Excel spreadsheets
5. **Pickle Files** - Serializing and deserializing Python objects

### Prerequisites:
- Basic understanding of Pandas DataFrames
- Familiarity with data formats (JSON, CSV, Excel)
- Internet connection for web-based examples

---

In [62]:
# Import necessary libraries
import pandas as pd  # For data manipulation and analysis
import json          # For JSON data handling

## 1. Working with JSON Data

JSON (JavaScript Object Notation) is a popular data format for APIs and web services. Pandas can easily convert JSON data to DataFrames and vice versa.

In [63]:
# Sample JSON data as a string (commonly received from APIs)
json_data = '''
[
  {"name": "Alice", "age": 25, "city": "Delhi"},
  {"name": "Bob", "age": 30, "city": "Mumbai"},
  {"name": "Charlie", "age": 35, "city": "Bangalore"}
]
'''

print("Original JSON data type:", type(json_data))
print("JSON string content:")
print(json_data)

# Convert JSON string to Python objects (list of dictionaries)
data = json.loads(json_data)
print("\nAfter parsing with json.loads():")
print("Type:", type(data))
print("Content:", data)

# Create a Pandas DataFrame from the parsed JSON data
df1 = pd.DataFrame(data)
print("\nConverted to Pandas DataFrame:")
display(df1)

Original JSON data type: <class 'str'>
JSON string content:

[
  {"name": "Alice", "age": 25, "city": "Delhi"},
  {"name": "Bob", "age": 30, "city": "Mumbai"},
  {"name": "Charlie", "age": 35, "city": "Bangalore"}
]


After parsing with json.loads():
Type: <class 'list'>
Content: [{'name': 'Alice', 'age': 25, 'city': 'Delhi'}, {'name': 'Bob', 'age': 30, 'city': 'Mumbai'}, {'name': 'Charlie', 'age': 35, 'city': 'Bangalore'}]

Converted to Pandas DataFrame:

      name  age       city
0    Alice   25      Delhi
1      Bob   30     Mumbai
2  Charlie   35  Bangalore

In [64]:
# Convert DataFrame back to JSON format
# orient='records' creates a list of dictionaries (most common format)
json_output = df1.to_json(orient='records')

print("DataFrame converted back to JSON:")
print("Type:", type(json_output))
print("Content:", json_output)

# You can also use other orientations:
# orient='split' - separate arrays for index, columns, and data
# orient='index' - dictionary with index as keys
# orient='columns' - dictionary with column names as keys
# orient='values' - just the values as a 2D array

DataFrame converted back to JSON:
Type: <class 'str'>
Content: [{"name":"Alice","age":25,"city":"Delhi"},{"name":"Bob","age":30,"city":"Mumbai"},{"name":"Charlie","age":35,"city":"Bangalore"}]

## 2. Reading CSV Files from the Web

Pandas can directly read CSV files from URLs without downloading them first. This is useful for accessing public datasets or APIs that return CSV data.

In [65]:
# Read CSV file directly from a URL
# This example uses the UCI Machine Learning Repository's Wine dataset
# header=None means the CSV file doesn't have column headers
# Pandas will automatically assign numeric column names (0, 1, 2, etc.)
df = pd.read_csv("https://archive.ics.uci.edu/ml/machine-learning-databases/wine/wine.data", header=None)

print("First 5 rows of the Wine dataset:")
display(df.head())

# Save the dataset locally as a CSV file for future use
df.to_csv('wine.csv', index=False)
print("\nDataset saved locally as 'wine.csv'")

# Note: The Wine dataset contains chemical analysis of wines from Italy
# It has 13 chemical attributes and a class label (wine type)

First 5 rows of the Wine dataset:

,0,1,2,3,4,5,6,7,8,9,10,11,12,13
0,1,14.23,1.71,2.43,15.6,127,2.80,3.06,0.28,2.29,5.64,1.04,3.92,1065
1,1,13.20,1.78,2.14,11.2,100,2.65,2.76,0.26,1.28,4.38,1.05,3.40,1050
2,1,13.16,2.36,2.67,18.6,101,2.80,3.24,0.30,2.81,5.68,1.03,3.17,1185
3,1,14.37,1.95,2.50,16.8,113,3.85,3.49,0.24,2.18,7.80,0.86,3.45,1480
4,1,13.24,2.59,2.87,21.0,118,2.80,2.69,0.39,1.82,4.32,1.04,2.93,735

Dataset saved locally as 'wine.csv'

## 3. Reading HTML Tables from Web Pages

Many websites contain data in HTML tables. Pandas can extract these tables directly from web pages using `pd.read_html()`. This requires the `requests` library and `lxml` or `beautifulsoup4`.

In [66]:
# Reading tables from HTML web pages
# This requires additional libraries: requests and lxml/beautifulsoup4
import requests
from io import StringIO

# URL of a Wikipedia page with tables
url = "https://en.wikipedia.org/wiki/Mobile_country_code"

# Set user agent to avoid being blocked by websites
headers = {
    "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36"
}

# Fetch the web page content
response = requests.get(url, headers=headers)

print("Response status code:", response.status_code)
print("Successfully fetched webpage content")

# Extract all tables from the HTML content
# match='Country' filters tables that contain the word "Country"
tables = pd.read_html(StringIO(response.text), match='Country')

print(f"\nFound {len(tables)} table(s) matching 'Country'")
print("First table preview:")
display(tables[0].head())

# Note: pd.read_html() returns a list of DataFrames
# Each DataFrame represents one table found on the page
# You can access specific tables by index: tables[0], tables[1], etc.

Response status code: 200
Successfully fetched webpage content

Found 1 table(s) matching 'Country'
First table preview:

,Mobile country code,Country,ISO 3166,Mobile network codes,National MNC authority,Remarks
0,289,A Abkhazia,GE-AB,List of mobile network codes in Abkhazia,NaN,MCC is not listed by ITU
1,412,Afghanistan,AF,List of mobile network codes in Afghanistan,NaN,NaN
2,276,Albania,AL,List of mobile network codes in Albania,NaN,NaN
3,603,Algeria,DZ,List of mobile network codes in Algeria,NaN,NaN
4,544,American Samoa (United States of America),AS,List of mobile network codes in American Samoa,NaN,NaN

## 4. Reading Excel Files

Excel files (.xls, .xlsx) are common in business environments. Pandas can read Excel files using `pd.read_excel()`. This requires the `openpyxl` or `xlrd` library.

In [67]:
# Read data from an Excel file
# This assumes you have a file named 'sample.xls' in the current directory
# For .xlsx files, use the same function - Pandas detects the format automatically
df_excel = pd.read_excel("sample.xls")

print("Excel file loaded successfully!")
print("Shape:", df_excel.shape)
print("Columns:", list(df_excel.columns))
print("\nFirst 5 rows:")
display(df_excel.head())

# Additional parameters you can use:
# sheet_name='Sheet1' - specify which sheet to read (default is first sheet)
# header=0 - specify which row contains column headers
# usecols=['A', 'B', 'C'] - specify which columns to read
# skiprows=2 - skip the first 2 rows

Excel file loaded successfully!
Shape: (9, 8)
Columns: [0, 'First Name', 'Last Name', 'Gender', 'Country', 'Age', 'Date', 'Id']

First 5 rows:

   0 First Name  Last Name  Gender        Country  Age        Date    Id
0  1      Dulce      Abril  Female  United States   32  15/10/2017  1562
1  2       Mara  Hashimoto  Female  Great Britain   25  16/08/2016  1582
2  3     Philip       Gent    Male         France   36  21/05/2015  2587
3  4   Kathleen     Hanner  Female  United States   25  15/10/2017  3549
4  5    Nereida    Magwood  Female  United States   58  16/08/2016  2468

## 5. Working with Pickle Files

Pickle is Python's way of serializing and deserializing objects. It's useful for saving Python objects (including DataFrames) to disk and loading them back later. Pickle files preserve data types and are faster than CSV for large datasets.

In [68]:
# Save DataFrame to a pickle file
# Pickle preserves all data types and is much faster than CSV for large datasets
# The file extension is typically .pkl or .pickle
df_excel.to_pickle("sample_xls_pickle.pkl")

print("DataFrame saved to pickle file: 'sample_xls_pickle.pkl'")
print("Pickle files are binary and preserve Python object structure")


# Load DataFrame from a pickle file
# This restores the exact DataFrame object that was saved
df_from_pickle = pd.read_pickle('sample_xls_pickle.pkl')

print("DataFrame loaded from pickle file:")
print("Shape:", df_from_pickle.shape)
print("Data types preserved:", df_from_pickle.dtypes.to_dict())
display(df_from_pickle.head())

# Verify that the loaded data matches the original
print("\nData integrity check:")
print("Original and loaded DataFrames are identical:", df_excel.equals(df_from_pickle))

DataFrame saved to pickle file: 'sample_xls_pickle.pkl'
Pickle files are binary and preserve Python object structure
DataFrame loaded from pickle file:
Shape: (9, 8)
Data types preserved: {0: dtype('int64'), 'First Name': dtype('O'), 'Last Name': dtype('O'), 'Gender': dtype('O'), 'Country': dtype('O'), 'Age': dtype('int64'), 'Date': dtype('O'), 'Id': dtype('int64')}

   0 First Name  Last Name  Gender        Country  Age        Date    Id
0  1      Dulce      Abril  Female  United States   32  15/10/2017  1562
1  2       Mara  Hashimoto  Female  Great Britain   25  16/08/2016  1582
2  3     Philip       Gent    Male         France   36  21/05/2015  2587
3  4   Kathleen     Hanner  Female  United States   25  15/10/2017  3549
4  5    Nereida    Magwood  Female  United States   58  16/08/2016  2468

Data integrity check:
Original and loaded DataFrames are identical: True

---

## Summary & Key Takeaways

### Data Source Reading Methods:
1. **JSON Data** - Use `json.loads()` then `pd.DataFrame()` for reading, `.to_json()` for writing
2. **Web CSV** - Use `pd.read_csv(url)` to read CSV files directly from URLs
3. **HTML Tables** - Use `pd.read_html()` with `requests` to extract tables from web pages
4. **Excel Files** - Use `pd.read_excel()` to read .xls and .xlsx files
5. **Pickle Files** - Use `.to_pickle()` and `pd.read_pickle()` for fast Python object serialization

### Best Practices:
- **JSON**: Use `orient='records'` for API-compatible format
- **Web Data**: Always set User-Agent headers when scraping websites
- **Excel**: Specify sheet names when working with multi-sheet workbooks
- **Pickle**: Only unpickle files from trusted sources (security risk)
- **Error Handling**: Always check if files exist and handle network errors

### Common File Extensions:
- `.json` - JSON data files
- `.csv` - Comma-separated values
- `.xls/.xlsx` - Microsoft Excel files
- `.pkl/.pickle` - Python pickle files
- `.html` - Web pages with tables

### Performance Tips:
- Pickle files are fastest for Python objects
- CSV is most portable across different systems
- Excel files preserve formatting but are slower to read
- JSON is human-readable and works well with APIs