# Ordinal Encoding

Ordinal Encoding is used to convert ordered categorical data into numbers.

Ordered categorical data means categories that have a clear ranking or order.

Examples:

- Small, Medium, Large
- Poor, Average, Good, Excellent
- Low, Medium, High

## Main Idea

Ordinal Encoding gives numbers based on the correct order of categories.

For example:

- Small = 0
- Medium = 1
- Large = 2

This is different from One-Hot Encoding because here the order matters.

## What We Will Learn

1. Import required libraries
2. Create a simple dataset
3. Define category order
4. Apply Ordinal Encoding
5. Convert encoded output into a DataFrame
6. Combine original and encoded data

## 1. Import Required Libraries

We import pandas for working with DataFrames.

We import `OrdinalEncoder` from scikit-learn to convert ordered categories into numbers.

In [1]:
import pandas as pd
import numpy as np
from sklearn.preprocessing import OrdinalEncoder

## 2. Create a Simple Dataset

Here we create a small dataset with two categorical columns:

- `Size`
- `Review`

Both columns have a natural order, so Ordinal Encoding is suitable for them.

In [2]:
data = pd.DataFrame(
    {
        "Size": ["Medium", "Small", "Large", "Small"],
        "Review": ["Good", "Excellent", "Fair", "Good"],
    }
)

### Dataset Observation

`Size` and `Review` are categorical columns.

They are not just names; they have meaningful order. That is why Ordinal Encoding is useful here.

## 3. Define the Correct Order

Before applying Ordinal Encoding, we must define the order manually.

This step is very important.

If we give the wrong order, the encoded numbers will also be wrong.

Here:

- `Small < Medium < Large`
- `Fair < Good < Excellent`

In [3]:
# define order for each column that need to Ordinal encoded
size_order = ["Small", "Medium", "Large"]
review_order = ["Fair", "Good", "Excellent"]

### Order Observation

The order is decided by us based on real meaning.

The encoder will not automatically know that `Large` is greater than `Medium`, or that `Excellent` is better than `Good`.

## 4. Create the Ordinal Encoder

Now we create an `OrdinalEncoder` object.

We pass the category order using the `categories` parameter.

The order must match the order of columns passed during encoding.

In [4]:
ordinal_encoder = OrdinalEncoder(categories=[size_order, review_order])

## 5. Apply Ordinal Encoding

Now we apply the encoder on the `Size` and `Review` columns.

`fit_transform()` learns the categories and converts them into numbers based on the order we provided.

In [5]:
encoded_data = ordinal_encoder.fit_transform(data[["Size", "Review"]])

## 6. View the Encoded Array

The encoded output is shown as a numeric array.

Each text category is replaced by a number according to its order.

In [6]:
encoded_data

array([[1., 1.],
       [0., 2.],
       [2., 0.],
       [0., 1.]])

### Encoded Array Observation

The encoded values follow the order we defined.

For `Size`:

- Small = 0
- Medium = 1
- Large = 2

For `Review`:

- Fair = 0
- Good = 1
- Excellent = 2

## 7. Convert Encoded Output Into DataFrame

The encoded array is converted into a pandas DataFrame.

We use clear column names:

- `Size_encoded`
- `Review_encoded`

This avoids confusion with the original columns.

In [7]:
encoded_df = pd.DataFrame(encoded_data, columns=["Size_encoded", "Review_encoded"])
encoded_df.head()

   Size_encoded  Review_encoded
0           1.0             1.0
1           0.0             2.0
2           2.0             0.0
3           0.0             1.0

## 8. Combine Original and Encoded Data

Finally, we combine the original data and the encoded data.

This helps us compare the original categories with their encoded numeric values.

In [8]:
# concat
encoded_combined_df = pd.concat([data, encoded_df], axis=1)
encoded_combined_df

     Size     Review  Size_encoded  Review_encoded
0  Medium       Good           1.0             1.0
1   Small  Excellent           0.0             2.0
2   Large       Fair           2.0             0.0
3   Small       Good           0.0             1.0

### Final Data Observation

The final DataFrame contains both original columns and encoded columns.

In real model training, we usually use the encoded numeric columns instead of the original text columns.

## Final Conclusion

Ordinal Encoding is used when categorical values have a natural order.

In this notebook, we encoded two ordered columns:

- `Size`
- `Review`

Important points:

1. Use Ordinal Encoding only when category order is meaningful.
2. Always define the correct order before encoding.
3. Wrong order can give wrong meaning to the model.
4. Ordinal Encoding is useful for input features like size, rating, level, or grade.
5. For unordered categories like city or color, One-Hot Encoding is usually better.